server:
  port: 9099

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://milo:123456@milo-eureka:7000/eureka/


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: order  #规则id
          uri: lb://order-service  # 转发目标服务
          predicates:
            - Path=/api/order/**  # 匹配路径
          filters:
            # Filter
            - StripPrefix=1  # 去除前缀级别
        - id: book
          uri: lb://book-service
          predicates:
            - Path=/api/book/**
          filters:
            - StripPrefix=1
        - id: oauth
          uri: lb://oauth-service
          predicates:
            - Path=/oauth/**


