server:
  port: 9000

spring:
  application:
    name: zuul-service

eureka:
  client:
    register-with-eureka: true #?????Eureka???
    fetch-registry: true #???Eureka?????????
    service-url: #Eureka??????????????
      defaultZone: http://milo:123456@milo-eureka:7000/eureka/
  instance:
    prefer-ip-address: true #?ip?????Eureka???
    ip-address: 127.0.0.1

zuul:
  prefix: /api #????
  routes:
    order-service: #????? ?????
      path: /order/** #??URL
      serviceId: order-service #???
      strip-prefix: false # ???????
    book-service:
      path: /book/**
      serviceId: book-service
      strip-prefix: false



