
server:
  port: 7000

spring:
  security:
    user:
      name: milo
      password: 123456

eureka:
  client:
    register-with-eureka: false #是否注册到Eureka服务中
    fetch-registry: false #是否从Eureka服务中获取注册信息
    service-url: #Eureka客户端与服务端进行交互的地址
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:${server.port}/eureka/