
server:
  port: 8050
#  tomcat:
#    uri-encoding: UTF-8

spring:
  application:
    name: book-service #指定服务名称
#  http:
#    encoding:
#      force: true
#      charset: UTF-8
#      enabled: true
eureka:
  client:
    register-with-eureka: true #是否注册到Eureka服务中
    fetch-registry: true #是否从Eureka服务中获取注册信息
    service-url: #Eureka客户端与服务端进行交互的地址
      defaultZone: http://milo:123456@milo-eureka:7000/eureka/
  instance:
    prefer-ip-address: true #把ip地址注册到Eureka服务中

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
    resource:
      loadBalanced: true
      token-info-uri: http://oauth-service/oauth/check_token